name: publish

on:
  push:
    branches:
      - source

jobs:
  build:
    name: Publish Webpage
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: '12'
      - run: npm ci
      - run: npm run gh-pages
      - run: |
          cd out
          git init
          git config user.name github-actions
          git config user.email github-actions@github.com
          git remote add origin https://vpukhanov:${{ secrets.GITHUB_TOKEN }}@github.com/vpukhanov/vpukhanov.github.io.git
          git add -A
          git commit -m "published from github actions"
          git push --force origin master